#include "cl_config_write.h"

#include <stdio.h>

int CL_WriteConfigFile(const char *path, CL_ConfigWriteFn writeBindings, CL_ConfigWriteFn writeCvars)
{
	FILE *f;

	if (!path || !path[0])
		return 0;

	f = fopen(path, "wt");
	if (!f)
		return 0;

	fprintf(f, "//\n// configuration file generated by EGL, modify at risk\n//\n");

	fprintf(f, "\n// key bindings\n");
	if (writeBindings)
		writeBindings(f);

	fprintf(f, "\n// console variables\n");
	if (writeCvars)
		writeCvars(f);

	// Preserve legacy behavior (even though embedded NUL is odd).
	fprintf(f, "\n\0");
	fclose(f);
	return 1;
}
